-- Seed admin user (password: Admin@1234 — bcrypt hash, cost 12)
-- Replace hash with fresh one generated by: node -e "const b=require('bcrypt');b.hash('Admin@1234',12).then(console.log)"
IF NOT EXISTS (SELECT 1 FROM users WHERE email = 'admin@model-jira.local')
BEGIN
  INSERT INTO users (id, name, email, password_hash, role)
  VALUES (
    NEWID(),
    'Admin',
    'admin@model-jira.local',
    '$2b$12$PLACEHOLDER_REPLACE_WITH_REAL_HASH',
    'admin'
  );
END;
